{{- if .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "swrtc-api.name" . }}
data:
  ICE_URL: {{ printf "https://ice.%s:8000" .Values.global.baseDomain }}
  API_PRIVATE_DOMAIN: {{ printf "%s.default.svc.cluster.local" ( include "swrtc-api.name" . ) }}
  API_DOMAIN: {{ printf "api.%s" .Values.global.baseDomain }}
  ENV_LEVEL: {{ .Values.global.environment }}
  {{- range $key, $val := .Values.config.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}