{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "swrtc-api.name" . }}
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}