pipeline:
  test:
    commands:
      - echo ${DRONE_DEPLOY_TO}
      - echo $${DRONE_DEPLOY_TO}
      - echo ${DRONE_TAG}
      - echo $${DRONE_TAG}
      - echo ${DRONE_COMMIT_SHA}
      - echo $${DRONE_COMMIT_SHA}
    when:
      event: push
      branch: test-build
  docker_stage:
    image: plugins/docker
    repo: andyet/talky-api-stage
    tags: 
      - ${DRONE_COMMIT_SHA##v}
      - latest
    secrets: [ docker_username, docker_password, docker_email ]
    when:
      event: tag
  docker_test:
    image: plugins/docker
    repo: andyet/talky-api-prod
    tags: 
      - ${DRONE_TAG}
    secrets: [ docker_username, docker_password, docker_email ]
    when:
      event: push
      branch: test-build
  docker_prod:
    image: plugins/docker
    repo: andyet/talky-api-prod
    tags: 
      - ${DRONE_TAG##v}
    secrets: [ docker_username, docker_password, docker_email ]
    when:
      event: deployment
  deploy_stage:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: talky-api-stage
    repo: andyet/talky-api-stage
    container: api
    namespace: default
    tag: 
    - ${DRONE_TAG##v}
    when:
      event: tag
    secrets: [ kubernetes_cert, kubernetes_server, kubernetes_token ]
  deploy_prod:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: talky-api-prod
    repo: andyet/talky-api-prod
    container: api
    namespace: default
    tag: 
    - ${DRONE_TAG##v}
    when:
      event: deploy
    secrets: [ kubernetes_cert, kubernetes_server, kubernetes_token ]
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]