pipeline:
  docker_stage:
    image: plugins/docker
    repo: andyet/talky-api
    tags: 
      - ${DRONE_COMMIT_SHA:0:8}
      - ${DRONE_TAG##v}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
  deploy_stage:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: talky-api-stage
    repo: andyet/talky-api
    container: api
    namespace: default
    tag: 
    - ${DRONE_TAG##v}
    when:
      event: tag
    secrets: [ kubernetes_cert, kubernetes_server, kubernetes_token ]
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: talky-api-prod
    repo: andyet/talky-api
    container: api
    namespace: default
    tag: ${DRONE_COMMIT_SHA:0:8}
    when:
      event: deployment
    secrets: [ kubernetes_cert, kubernetes_server, kubernetes_token ]
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]