pipeline:
  docker_stage:
    image: plugins/docker
    repo: andyet/talky-api-stage
    tags: 
      - ${DRONE_TAG##v}
      - latest
    secrets: [ docker_username, docker_password, docker_email ]
    when:
      event: push
      branch: stage
  docker_prod:
    image: plugins/docker
    repo: andyet/talky-api-prod
    tags: 
      - ${DRONE_TAG##v}
    secrets: [ docker_username, docker_password, docker_email ]
    when:
      event: deployment
  deploy_stage:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: talky-api-stage
    repo: andyet/talky-api-stage
    container: api
    namespace: default
    tag: 
    - latest
    when:
      event: push
      branch: stage
    secrets: [ kubernetes_cert, kubernetes_server, kubernetes_token ]
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]