apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "prosody.name" . }}
  labels:
    chart: {{ template "prosody.chart" . }}
    name: {{ template "prosody.name" . }}
spec:
  replicas: {{ default 1 .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ default 3 .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      name: {{ template "prosody.name" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ template "prosody.name" . }}
      name: {{ template "prosody.name" . }}
    spec:
      dnsPolicy: {{ default "ClusterFirst" .Values.deployment.dnsPolicy }}
      imagePullSecrets:
      - name: {{ required "You must provide imagePullSecrets!" .Values.global.imagePullSecrets }}
      restartPolicy: {{ default "Always" .Values.deployment.restartPolicy }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | trimSuffix "\n" }}
      {{- end }}
      {{- if .Values.deployment.volumes }}
      volumes:
      {{- range .Values.deployment.volumes }}
      - name: {{ .name }}
        configMap:
          name: {{ printf "prosody-config-%s" $.Values.global.environment }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ template "prosody.name" . }}
        image: {{ printf "%s:%s" .Values.deployment.image.repository .Values.deployment.image.tag }}
        imagePullPolicy: {{ default "Always" .Values.deployment.image.pullPolicy }}
        ports:
        {{- range .Values.deployment.ports }}
        - containerPort: {{ .containerPort }}
          {{- if .hostPort }}
          hostPort: {{ .hostPort }}
          {{- end }}
          {{- if .name }}
          name: {{ .name }}
          {{- end }}
          {{- if .protocol }}
          protocol: {{ .protocol }}
          {{- else }}
          protocol: TCP
          {{- end }}
        {{- end }}
        {{- if .Values.deployment.volumes }}
        volumeMounts:
        {{- range .Values.deployment.volumes }}
        - mountPath: {{ .mountPath }}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
          tcpSocket:
            port: {{ .Values.global.prosodyPort }}